; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=z15 < %s -mtriple=s390x-linux-gnu | FileCheck %s
;
; Test volatile memmoves of some small constant lengths that should be done either
; with load/store combinations, or with libcall.

declare void @llvm.memmove.p0.p0.i64(ptr nocapture, ptr nocapture, i64, i1) nounwind

define void @fun1(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lb %r0, 0(%r2)
; CHECK-NEXT:    stc %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 2 %Dst, ptr align 2 %Src, i64 1, i1 true)
  ret void
}

define void @fun2(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh %r0, 0(%r2)
; CHECK-NEXT:    sth %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 2 %Dst, ptr align 2 %Src, i64 2, i1 true)
  ret void
}

define void @fun3(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh %r0, 0(%r2)
; CHECK-NEXT:    lb %r1, 2(%r2)
; CHECK-NEXT:    stc %r1, 2(%r3)
; CHECK-NEXT:    sth %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 2 %Dst, ptr align 2 %Src, i64 3, i1 true)
  ret void
}

define void @fun4(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l %r0, 0(%r2)
; CHECK-NEXT:    st %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 4 %Dst, ptr align 4 %Src, i64 4, i1 true)
  ret void
}

define void @fun4_unalignedSrc(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun4_unalignedSrc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 4
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 2 %Dst, ptr align 4 %Src, i64 4, i1 true)
  ret void
}

define void @fun5(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l %r0, 0(%r2)
; CHECK-NEXT:    lb %r1, 4(%r2)
; CHECK-NEXT:    stc %r1, 4(%r3)
; CHECK-NEXT:    st %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 4 %Dst, ptr align 4 %Src, i64 5, i1 true)
  ret void
}

define void @fun6(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l %r0, 0(%r2)
; CHECK-NEXT:    lh %r1, 4(%r2)
; CHECK-NEXT:    sth %r1, 4(%r3)
; CHECK-NEXT:    st %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 4 %Dst, ptr align 4 %Src, i64 6, i1 true)
  ret void
}

define void @fun7(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 7
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 4 %Dst, ptr align 4 %Src, i64 7, i1 true)
  ret void
}

define void @fun8(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    stg %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 8, i1 true)
  ret void
}

define void @fun9(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    lb %r1, 8(%r2)
; CHECK-NEXT:    stc %r1, 8(%r3)
; CHECK-NEXT:    stg %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 9, i1 true)
  ret void
}

define void @fun10(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun10:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    lh %r1, 8(%r2)
; CHECK-NEXT:    sth %r1, 8(%r3)
; CHECK-NEXT:    stg %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 10, i1 true)
  ret void
}

define void @fun11(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun11:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 11
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 11, i1 true)
  ret void
}

define void @fun12(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun12:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lg %r0, 0(%r2)
; CHECK-NEXT:    l %r1, 8(%r2)
; CHECK-NEXT:    st %r1, 8(%r3)
; CHECK-NEXT:    stg %r0, 0(%r3)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 12, i1 true)
  ret void
}

define void @fun13(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun13:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 13
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 13, i1 true)
  ret void
}

define void @fun14(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun14:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 14
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 14, i1 true)
  ret void
}

define void @fun15(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun15:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 15
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 15, i1 true)
  ret void
}

define void @fun16(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 16, i1 true)
  ret void
}

define void @fun17(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun17:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    lb %r0, 16(%r2)
; CHECK-NEXT:    stc %r0, 16(%r3)
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 17, i1 true)
  ret void
}

define void @fun17_unalignedSrc(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun17_unalignedSrc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 17
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 4 %Src, i64 17, i1 true)
  ret void
}

define void @fun18(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun18:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    lh %r0, 16(%r2)
; CHECK-NEXT:    sth %r0, 16(%r3)
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 18, i1 true)
  ret void
}

define void @fun18_unalignedDst(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun18_unalignedDst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 18
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 2 %Dst, ptr align 8 %Src, i64 18, i1 true)
  ret void
}

define void @fun19(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun19:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 19
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 19, i1 true)
  ret void
}

define void @fun20(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun20:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    l %r0, 16(%r2)
; CHECK-NEXT:    st %r0, 16(%r3)
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 20, i1 true)
  ret void
}

define void @fun20_localDst(ptr %Src, i8 %val) {
; CHECK-LABEL: fun20_localDst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    aghi %r15, -184
; CHECK-NEXT:    .cfi_def_cfa_offset 344
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    l %r0, 16(%r2)
; CHECK-NEXT:    st %r0, 180(%r15)
; CHECK-NEXT:    vst %v0, 164(%r15), 3
; CHECK-NEXT:    aghi %r15, 184
; CHECK-NEXT:    br %r14
  %Dst = alloca [20 x i8]
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 20, i1 true)
  ret void
}

define void @fun21(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun21:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 21
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 21, i1 true)
  ret void
}

define void @fun22(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun22:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 22
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 22, i1 true)
  ret void
}

define void @fun23(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun23:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 23
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 23, i1 true)
  ret void
}

define void @fun24(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun24:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    lg %r0, 16(%r2)
; CHECK-NEXT:    stg %r0, 16(%r3)
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 24, i1 true)
  ret void
}

define void @fun25(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun25:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 25
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 25, i1 true)
  ret void
}

define void @fun26(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun26:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 26
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 26, i1 true)
  ret void
}

define void @fun27(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun27:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 27
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 27, i1 true)
  ret void
}

define void @fun28(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun28:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 28
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 28, i1 true)
  ret void
}

define void @fun29(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun29:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 29
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 29, i1 true)
  ret void
}

define void @fun30(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun30:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 30
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 30, i1 true)
  ret void
}

define void @fun31(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 31
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 31, i1 true)
  ret void
}

define void @fun32(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl %v0, 0(%r2), 3
; CHECK-NEXT:    vl %v1, 16(%r2), 3
; CHECK-NEXT:    vst %v1, 16(%r3), 3
; CHECK-NEXT:    vst %v0, 0(%r3), 3
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 32, i1 true)
  ret void
}

define void @fun33(ptr %Src, ptr %Dst, i8 %val) {
; CHECK-LABEL: fun33:
; CHECK:       # %bb.0:
; CHECK-NEXT:    stmg %r14, %r15, 112(%r15)
; CHECK-NEXT:    .cfi_offset %r14, -48
; CHECK-NEXT:    .cfi_offset %r15, -40
; CHECK-NEXT:    aghi %r15, -160
; CHECK-NEXT:    .cfi_def_cfa_offset 320
; CHECK-NEXT:    lgr %r0, %r2
; CHECK-NEXT:    lgr %r2, %r3
; CHECK-NEXT:    lgr %r3, %r0
; CHECK-NEXT:    lghi %r4, 33
; CHECK-NEXT:    brasl %r14, memmove@PLT
; CHECK-NEXT:    lmg %r14, %r15, 272(%r15)
; CHECK-NEXT:    br %r14
  call void @llvm.memmove.p0.p0.i64(ptr align 8 %Dst, ptr align 8 %Src, i64 33, i1 true)
  ret void
}
