; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7 %s -o - | FileCheck %s --check-prefixes=CHECK-ARM
; RUN: llc -mtriple=thumb-eabi -mcpu=arm7tdmi %s -o - | FileCheck %s --check-prefix=CHECK-T1
; RUN: llc -mtriple=thumb-eabi -mcpu=arm1156t2-s -mattr=+thumb2 %s -o - | FileCheck %s --check-prefix=CHECK-T2

declare void @otherfn()

define void @cmp_shiftx(i32 %x, i32 %y) {
; CHECK-ARM-LABEL: cmp_shiftx:
; CHECK-ARM:       @ %bb.0: @ %entry
; CHECK-ARM-NEXT:    cmp r1, r0, lsl #1
; CHECK-ARM-NEXT:    bxne lr
; CHECK-ARM-NEXT:  .LBB0_1: @ %if.then
; CHECK-ARM-NEXT:    b otherfn
;
; CHECK-T1-LABEL: cmp_shiftx:
; CHECK-T1:       @ %bb.0: @ %entry
; CHECK-T1-NEXT:    .save {r7, lr}
; CHECK-T1-NEXT:    push {r7, lr}
; CHECK-T1-NEXT:    lsls r0, r0, #1
; CHECK-T1-NEXT:    cmp r0, r1
; CHECK-T1-NEXT:    bne .LBB0_2
; CHECK-T1-NEXT:  @ %bb.1: @ %if.then
; CHECK-T1-NEXT:    bl otherfn
; CHECK-T1-NEXT:  .LBB0_2: @ %if.end
; CHECK-T1-NEXT:    pop {r7}
; CHECK-T1-NEXT:    pop {r0}
; CHECK-T1-NEXT:    bx r0
;
; CHECK-T2-LABEL: cmp_shiftx:
; CHECK-T2:       @ %bb.0: @ %entry
; CHECK-T2-NEXT:    cmp.w r1, r0, lsl #1
; CHECK-T2-NEXT:    it ne
; CHECK-T2-NEXT:    bxne lr
; CHECK-T2-NEXT:    b otherfn
entry:
  %shl = shl i32 %x, 1
  %cmp = icmp eq i32 %shl, %y
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @otherfn()
  ret void

if.end:                                           ; preds = %entry
  ret void
}

define void @cmp_shifty(i32 %x, i32 %y) {
; CHECK-ARM-LABEL: cmp_shifty:
; CHECK-ARM:       @ %bb.0: @ %entry
; CHECK-ARM-NEXT:    cmp r0, r1, lsl #1
; CHECK-ARM-NEXT:    bxne lr
; CHECK-ARM-NEXT:  .LBB1_1: @ %if.then
; CHECK-ARM-NEXT:    b otherfn
;
; CHECK-T1-LABEL: cmp_shifty:
; CHECK-T1:       @ %bb.0: @ %entry
; CHECK-T1-NEXT:    .save {r7, lr}
; CHECK-T1-NEXT:    push {r7, lr}
; CHECK-T1-NEXT:    lsls r1, r1, #1
; CHECK-T1-NEXT:    cmp r0, r1
; CHECK-T1-NEXT:    bne .LBB1_2
; CHECK-T1-NEXT:  @ %bb.1: @ %if.then
; CHECK-T1-NEXT:    bl otherfn
; CHECK-T1-NEXT:  .LBB1_2: @ %if.end
; CHECK-T1-NEXT:    pop {r7}
; CHECK-T1-NEXT:    pop {r0}
; CHECK-T1-NEXT:    bx r0
;
; CHECK-T2-LABEL: cmp_shifty:
; CHECK-T2:       @ %bb.0: @ %entry
; CHECK-T2-NEXT:    cmp.w r0, r1, lsl #1
; CHECK-T2-NEXT:    it ne
; CHECK-T2-NEXT:    bxne lr
; CHECK-T2-NEXT:    b otherfn
entry:
  %shl = shl i32 %y, 1
  %cmp = icmp eq i32 %x, %shl
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @otherfn()
  ret void

if.end:                                           ; preds = %entry
  ret void
}

define void @cmn_shiftx(i32 %x, i32 %y) {
; CHECK-ARM-LABEL: cmn_shiftx:
; CHECK-ARM:       @ %bb.0: @ %entry
; CHECK-ARM-NEXT:    cmn r1, r0, lsl #1
; CHECK-ARM-NEXT:    bxne lr
; CHECK-ARM-NEXT:  .LBB2_1: @ %if.then
; CHECK-ARM-NEXT:    b otherfn
;
; CHECK-T1-LABEL: cmn_shiftx:
; CHECK-T1:       @ %bb.0: @ %entry
; CHECK-T1-NEXT:    .save {r7, lr}
; CHECK-T1-NEXT:    push {r7, lr}
; CHECK-T1-NEXT:    lsls r0, r0, #1
; CHECK-T1-NEXT:    cmn r0, r1
; CHECK-T1-NEXT:    bne .LBB2_2
; CHECK-T1-NEXT:  @ %bb.1: @ %if.then
; CHECK-T1-NEXT:    bl otherfn
; CHECK-T1-NEXT:  .LBB2_2: @ %if.end
; CHECK-T1-NEXT:    pop {r7}
; CHECK-T1-NEXT:    pop {r0}
; CHECK-T1-NEXT:    bx r0
;
; CHECK-T2-LABEL: cmn_shiftx:
; CHECK-T2:       @ %bb.0: @ %entry
; CHECK-T2-NEXT:    cmn.w r1, r0, lsl #1
; CHECK-T2-NEXT:    it ne
; CHECK-T2-NEXT:    bxne lr
; CHECK-T2-NEXT:    b otherfn
entry:
  %shl = shl i32 %x, 1
  %sub = sub nsw i32 0, %y
  %cmp = icmp eq i32 %shl, %sub
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @otherfn()
  ret void

if.end:                                           ; preds = %entry
  ret void
}

define void @cmn_shifty(i32 %x, i32 %y) {
; CHECK-ARM-LABEL: cmn_shifty:
; CHECK-ARM:       @ %bb.0: @ %entry
; CHECK-ARM-NEXT:    cmn r0, r1, lsl #1
; CHECK-ARM-NEXT:    bxne lr
; CHECK-ARM-NEXT:  .LBB3_1: @ %if.then
; CHECK-ARM-NEXT:    b otherfn
;
; CHECK-T1-LABEL: cmn_shifty:
; CHECK-T1:       @ %bb.0: @ %entry
; CHECK-T1-NEXT:    .save {r7, lr}
; CHECK-T1-NEXT:    push {r7, lr}
; CHECK-T1-NEXT:    lsls r1, r1, #1
; CHECK-T1-NEXT:    cmn r0, r1
; CHECK-T1-NEXT:    bne .LBB3_2
; CHECK-T1-NEXT:  @ %bb.1: @ %if.then
; CHECK-T1-NEXT:    bl otherfn
; CHECK-T1-NEXT:  .LBB3_2: @ %if.end
; CHECK-T1-NEXT:    pop {r7}
; CHECK-T1-NEXT:    pop {r0}
; CHECK-T1-NEXT:    bx r0
;
; CHECK-T2-LABEL: cmn_shifty:
; CHECK-T2:       @ %bb.0: @ %entry
; CHECK-T2-NEXT:    cmn.w r0, r1, lsl #1
; CHECK-T2-NEXT:    it ne
; CHECK-T2-NEXT:    bxne lr
; CHECK-T2-NEXT:    b otherfn
entry:
  %shl.neg = mul i32 %y, -2
  %cmp = icmp eq i32 %x, %shl.neg
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  tail call void @otherfn()
  ret void

if.end:                                           ; preds = %entry
  ret void
}
