; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p loop-vectorize -vplan-print-after="optimize$" -force-vector-width=4 -disable-output -enable-early-exit-vectorization-with-side-effects -force-target-supports-masked-memory-ops < %s 2>&1 | FileCheck %s -check-prefix=OPTIMIZED

; REQUIRES: asserts

define void @loop_contains_store_condition_load_has_single_user(ptr dereferenceable(40) noalias %array, ptr align 2 dereferenceable(40) readonly %pred) {
; OPTIMIZED-LABEL: VPlan for loop in 'loop_contains_store_condition_load_has_single_user'
; OPTIMIZED:  VPlan 'Initial VPlan for VF={4},UF>=1' {
; OPTIMIZED-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; OPTIMIZED-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; OPTIMIZED-NEXT:  Live-in vp<[[VP2:%[0-9]+]]> = vector-trip-count
; OPTIMIZED-NEXT:  Live-in ir<20> = original trip-count
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<entry>:
; OPTIMIZED-NEXT:  Successor(s): scalar.ph, vector.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  vector.ph:
; OPTIMIZED-NEXT:  Successor(s): vector loop
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  <x1> vector loop: {
; OPTIMIZED-NEXT:    vector.body:
; OPTIMIZED-NEXT:      EMIT vp<[[VP3:%[0-9]+]]> = CANONICAL-INDUCTION ir<0>, vp<%index.next>
; OPTIMIZED-NEXT:      vp<[[VP4:%[0-9]+]]> = SCALAR-STEPS vp<[[VP3]]>, ir<1>, vp<[[VP0]]>
; OPTIMIZED-NEXT:      CLONE ir<%st.addr> = getelementptr inbounds nuw ir<%array>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      CLONE ir<%ee.addr> = getelementptr inbounds nuw ir<%pred>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      vp<[[VP5:%[0-9]+]]> = vector-pointer inbounds nuw ir<%ee.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.val> = load vp<[[VP5]]>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.cond> = icmp sgt ir<%ee.val>, ir<500>
; OPTIMIZED-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = first-active-lane ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<%uncountable.exit.mask> = active lane mask ir<0>, vp<[[VP6]]>, ir<1>
; OPTIMIZED-NEXT:      vp<[[VP7:%[0-9]+]]> = vector-pointer inbounds nuw ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%data> = load vp<[[VP7]]>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      WIDEN ir<%inc> = add nsw ir<%data>, ir<1>
; OPTIMIZED-NEXT:      vp<[[VP8:%[0-9]+]]> = vector-pointer inbounds nuw ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN store vp<[[VP8]]>, ir<%inc>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = any-of ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = icmp eq vp<%index.next>, vp<[[VP2]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = or vp<[[VP9]]>, vp<[[VP10]]>
; OPTIMIZED-NEXT:      EMIT branch-on-cond vp<[[VP11]]>
; OPTIMIZED-NEXT:    No successors
; OPTIMIZED-NEXT:  }
; OPTIMIZED-NEXT:  Successor(s): middle.block
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  middle.block:
; OPTIMIZED-NEXT:    EMIT vp<[[VP13:%[0-9]+]]> = add vp<[[VP3]]>, vp<[[VP6]]>
; OPTIMIZED-NEXT:    EMIT vp<[[VP14:%[0-9]+]]> = icmp eq vp<[[VP13]]>, ir<20>
; OPTIMIZED-NEXT:    EMIT branch-on-cond vp<[[VP14]]>
; OPTIMIZED-NEXT:  Successor(s): ir-bb<exit>, scalar.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<exit>:
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  scalar.ph:
; OPTIMIZED-NEXT:    EMIT-SCALAR vp<%bc.resume.val> = phi [ vp<[[VP13]]>, middle.block ], [ ir<0>, ir-bb<entry> ]
; OPTIMIZED-NEXT:  Successor(s): ir-bb<for.body>
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<for.body>:
; OPTIMIZED-NEXT:    IR   %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ] (extra operand: vp<%bc.resume.val> from scalar.ph)
; OPTIMIZED-NEXT:    IR   %st.addr = getelementptr inbounds nuw i16, ptr %array, i64 %iv
; OPTIMIZED-NEXT:    IR   %data = load i16, ptr %st.addr, align 2
; OPTIMIZED-NEXT:    IR   %inc = add nsw i16 %data, 1
; OPTIMIZED-NEXT:    IR   store i16 %inc, ptr %st.addr, align 2
; OPTIMIZED-NEXT:    IR   %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
; OPTIMIZED-NEXT:    IR   %ee.val = load i16, ptr %ee.addr, align 2
; OPTIMIZED-NEXT:    IR   %ee.cond = icmp sgt i16 %ee.val, 500
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-NEXT:  }
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ]
  %st.addr = getelementptr inbounds nuw i16, ptr %array, i64 %iv
  %data = load i16, ptr %st.addr, align 2
  %inc = add nsw i16 %data, 1
  store i16 %inc, ptr %st.addr, align 2
  %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
  %ee.val = load i16, ptr %ee.addr, align 2
  %ee.cond = icmp sgt i16 %ee.val, 500
  br i1 %ee.cond, label %exit, label %for.inc

for.inc:
  %iv.next = add nuw nsw i64 %iv, 1
  %counted.cond = icmp eq i64 %iv.next, 20
  br i1 %counted.cond, label %exit, label %for.body

exit:
  ret void
}

define void @loop_contains_store_after_uncountable_exit(ptr dereferenceable(40) noalias %array, ptr align 2 dereferenceable(40) readonly %pred) {
; OPTIMIZED-LABEL: VPlan for loop in 'loop_contains_store_after_uncountable_exit'
; OPTIMIZED:  VPlan 'Initial VPlan for VF={4},UF>=1' {
; OPTIMIZED-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; OPTIMIZED-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; OPTIMIZED-NEXT:  Live-in vp<[[VP2:%[0-9]+]]> = vector-trip-count
; OPTIMIZED-NEXT:  Live-in ir<20> = original trip-count
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<entry>:
; OPTIMIZED-NEXT:  Successor(s): scalar.ph, vector.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  vector.ph:
; OPTIMIZED-NEXT:  Successor(s): vector loop
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  <x1> vector loop: {
; OPTIMIZED-NEXT:    vector.body:
; OPTIMIZED-NEXT:      EMIT vp<[[VP3:%[0-9]+]]> = CANONICAL-INDUCTION ir<0>, vp<%index.next>
; OPTIMIZED-NEXT:      vp<[[VP4:%[0-9]+]]> = SCALAR-STEPS vp<[[VP3]]>, ir<1>, vp<[[VP0]]>
; OPTIMIZED-NEXT:      CLONE ir<%ee.addr> = getelementptr inbounds nuw ir<%pred>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      vp<[[VP5:%[0-9]+]]> = vector-pointer inbounds nuw ir<%ee.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.val> = load vp<[[VP5]]>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.cond> = icmp sgt ir<%ee.val>, ir<500>
; OPTIMIZED-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = first-active-lane ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<%uncountable.exit.mask> = active lane mask ir<0>, vp<[[VP6]]>, ir<1>
; OPTIMIZED-NEXT:      CLONE ir<%st.addr> = getelementptr ir<%array>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      vp<[[VP7:%[0-9]+]]> = vector-pointer ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%data> = load vp<[[VP7]]>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      WIDEN ir<%inc> = add nsw ir<%data>, ir<1>
; OPTIMIZED-NEXT:      vp<[[VP8:%[0-9]+]]> = vector-pointer ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN store vp<[[VP8]]>, ir<%inc>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = any-of ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = icmp eq vp<%index.next>, vp<[[VP2]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = or vp<[[VP9]]>, vp<[[VP10]]>
; OPTIMIZED-NEXT:      EMIT branch-on-cond vp<[[VP11]]>
; OPTIMIZED-NEXT:    No successors
; OPTIMIZED-NEXT:  }
; OPTIMIZED-NEXT:  Successor(s): middle.block
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  middle.block:
; OPTIMIZED-NEXT:    EMIT vp<[[VP13:%[0-9]+]]> = add vp<[[VP3]]>, vp<[[VP6]]>
; OPTIMIZED-NEXT:    EMIT vp<[[VP14:%[0-9]+]]> = icmp eq vp<[[VP13]]>, ir<20>
; OPTIMIZED-NEXT:    EMIT branch-on-cond vp<[[VP14]]>
; OPTIMIZED-NEXT:  Successor(s): ir-bb<exit>, scalar.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<exit>:
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  scalar.ph:
; OPTIMIZED-NEXT:    EMIT-SCALAR vp<%bc.resume.val> = phi [ vp<[[VP13]]>, middle.block ], [ ir<0>, ir-bb<entry> ]
; OPTIMIZED-NEXT:  Successor(s): ir-bb<for.body>
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<for.body>:
; OPTIMIZED-NEXT:    IR   %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ] (extra operand: vp<%bc.resume.val> from scalar.ph)
; OPTIMIZED-NEXT:    IR   %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
; OPTIMIZED-NEXT:    IR   %ee.val = load i16, ptr %ee.addr, align 2
; OPTIMIZED-NEXT:    IR   %ee.cond = icmp sgt i16 %ee.val, 500
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-NEXT:  }
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ]
  %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
  %ee.val = load i16, ptr %ee.addr, align 2
  %ee.cond = icmp sgt i16 %ee.val, 500
  br i1 %ee.cond, label %exit, label %for.inc

for.inc:
  %st.addr = getelementptr inbounds nuw i16, ptr %array, i64 %iv
  %data = load i16, ptr %st.addr, align 2
  %inc = add nsw i16 %data, 1
  store i16 %inc, ptr %st.addr, align 2
  %iv.next = add nuw nsw i64 %iv, 1
  %counted.cond = icmp eq i64 %iv.next, 20
  br i1 %counted.cond, label %exit, label %for.body

exit:
  ret void
}

define i16 @uncountable_exit_with_live_out(ptr dereferenceable(40) noalias %array, ptr align 2 dereferenceable(40) readonly %pred) {
; OPTIMIZED-LABEL: VPlan for loop in 'uncountable_exit_with_live_out'
; OPTIMIZED:  VPlan 'Initial VPlan for VF={4},UF>=1' {
; OPTIMIZED-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; OPTIMIZED-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; OPTIMIZED-NEXT:  Live-in vp<[[VP2:%[0-9]+]]> = vector-trip-count
; OPTIMIZED-NEXT:  Live-in ir<20> = original trip-count
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<entry>:
; OPTIMIZED-NEXT:  Successor(s): scalar.ph, vector.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  vector.ph:
; OPTIMIZED-NEXT:  Successor(s): vector loop
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  <x1> vector loop: {
; OPTIMIZED-NEXT:    vector.body:
; OPTIMIZED-NEXT:      EMIT vp<[[VP3:%[0-9]+]]> = CANONICAL-INDUCTION ir<0>, vp<%index.next>
; OPTIMIZED-NEXT:      vp<[[VP4:%[0-9]+]]> = SCALAR-STEPS vp<[[VP3]]>, ir<1>, vp<[[VP0]]>
; OPTIMIZED-NEXT:      CLONE ir<%st.addr> = getelementptr inbounds nuw ir<%array>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      CLONE ir<%ee.addr> = getelementptr inbounds nuw ir<%pred>, vp<[[VP4]]>
; OPTIMIZED-NEXT:      vp<[[VP5:%[0-9]+]]> = vector-pointer inbounds nuw ir<%ee.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.val> = load vp<[[VP5]]>
; OPTIMIZED-NEXT:      WIDEN ir<%ee.cond> = icmp sgt ir<%ee.val>, ir<500>
; OPTIMIZED-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = first-active-lane ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<%uncountable.exit.mask> = active lane mask ir<0>, vp<[[VP6]]>, ir<1>
; OPTIMIZED-NEXT:      vp<[[VP7:%[0-9]+]]> = vector-pointer inbounds nuw ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN ir<%data> = load vp<[[VP7]]>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      WIDEN ir<%inc> = add nsw ir<%data>, ir<1>
; OPTIMIZED-NEXT:      vp<[[VP8:%[0-9]+]]> = vector-pointer inbounds nuw ir<%st.addr>
; OPTIMIZED-NEXT:      WIDEN store vp<[[VP8]]>, ir<%inc>, vp<%uncountable.exit.mask>
; OPTIMIZED-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = any-of ir<%ee.cond>
; OPTIMIZED-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = icmp eq vp<%index.next>, vp<[[VP2]]>
; OPTIMIZED-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = or vp<[[VP9]]>, vp<[[VP10]]>
; OPTIMIZED-NEXT:      EMIT branch-on-cond vp<[[VP11]]>
; OPTIMIZED-NEXT:    No successors
; OPTIMIZED-NEXT:  }
; OPTIMIZED-NEXT:  Successor(s): middle.block
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  middle.block:
; OPTIMIZED-NEXT:    EMIT vp<[[VP13:%[0-9]+]]> = extract-last-part ir<%data>
; OPTIMIZED-NEXT:    EMIT vp<[[VP14:%[0-9]+]]> = extract-last-lane vp<[[VP13]]>
; OPTIMIZED-NEXT:    EMIT vp<[[VP15:%[0-9]+]]> = add vp<[[VP3]]>, vp<[[VP6]]>
; OPTIMIZED-NEXT:    EMIT vp<[[VP16:%[0-9]+]]> = icmp eq vp<[[VP15]]>, ir<20>
; OPTIMIZED-NEXT:    EMIT branch-on-cond vp<[[VP16]]>
; OPTIMIZED-NEXT:  Successor(s): ir-bb<exit>, scalar.ph
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<exit>:
; OPTIMIZED-NEXT:    IR   %data.lcssa = phi i16 [ %data, %for.inc ], [ %data, %for.body ] (extra operand: vp<[[VP14]]> from middle.block)
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  scalar.ph:
; OPTIMIZED-NEXT:    EMIT-SCALAR vp<%bc.resume.val> = phi [ vp<[[VP15]]>, middle.block ], [ ir<0>, ir-bb<entry> ]
; OPTIMIZED-NEXT:  Successor(s): ir-bb<for.body>
; OPTIMIZED-EMPTY:
; OPTIMIZED-NEXT:  ir-bb<for.body>:
; OPTIMIZED-NEXT:    IR   %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ] (extra operand: vp<%bc.resume.val> from scalar.ph)
; OPTIMIZED-NEXT:    IR   %st.addr = getelementptr inbounds nuw i16, ptr %array, i64 %iv
; OPTIMIZED-NEXT:    IR   %data = load i16, ptr %st.addr, align 2
; OPTIMIZED-NEXT:    IR   %inc = add nsw i16 %data, 1
; OPTIMIZED-NEXT:    IR   store i16 %inc, ptr %st.addr, align 2
; OPTIMIZED-NEXT:    IR   %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
; OPTIMIZED-NEXT:    IR   %ee.val = load i16, ptr %ee.addr, align 2
; OPTIMIZED-NEXT:    IR   %ee.cond = icmp sgt i16 %ee.val, 500
; OPTIMIZED-NEXT:  No successors
; OPTIMIZED-NEXT:  }
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.inc ]
  %st.addr = getelementptr inbounds nuw i16, ptr %array, i64 %iv
  %data = load i16, ptr %st.addr, align 2
  %inc = add nsw i16 %data, 1
  store i16 %inc, ptr %st.addr, align 2
  %ee.addr = getelementptr inbounds nuw i16, ptr %pred, i64 %iv
  %ee.val = load i16, ptr %ee.addr, align 2
  %ee.cond = icmp sgt i16 %ee.val, 500
  br i1 %ee.cond, label %exit, label %for.inc

for.inc:
  %iv.next = add nuw nsw i64 %iv, 1
  %counted.cond = icmp eq i64 %iv.next, 20
  br i1 %counted.cond, label %exit, label %for.body

exit:
  ret i16 %data
}


