; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=riscv64 -passes=loop-vectorize -mattr=+v -tail-folding-policy=prefer-fold-tail -force-tail-folding-style=data -scalable-vectorization=on -force-vector-width=16 -force-vector-interleave=1 -vplan-print-after=removeRedundantCanonicalIVs -disable-output %s 2>&1 | FileCheck %s

define void @redundant_widecaniv(ptr noalias %p, ptr noalias %q, i8 %guard) {
; CHECK-LABEL: VPlan for loop in 'redundant_widecaniv'
; CHECK:  VPlan 'Initial VPlan for VF={vscale x 16},UF>=1' {
; CHECK-NEXT:  Live-in vp<[[VP0:%[0-9]+]]> = VF
; CHECK-NEXT:  Live-in vp<[[VP1:%[0-9]+]]> = VF * UF
; CHECK-NEXT:  Live-in vp<[[VP2:%[0-9]+]]> = vector-trip-count
; CHECK-NEXT:  Live-in ir<1024> = original trip-count
; CHECK-EMPTY:
; CHECK-NEXT:  ir-bb<entry>:
; CHECK-NEXT:    IR   %conv = zext i8 %guard to i32
; CHECK-NEXT:  Successor(s): scalar.ph, vector.ph
; CHECK-EMPTY:
; CHECK-NEXT:  vector.ph:
; CHECK-NEXT:  Successor(s): vector loop
; CHECK-EMPTY:
; CHECK-NEXT:  <x1> vector loop: {
; CHECK-NEXT:  vp<[[VP4:%[0-9]+]]> = CANONICAL-IV
; CHECK-EMPTY:
; CHECK-NEXT:    vector.body:
; CHECK-NEXT:      ir<%ix.024> = WIDEN-INDUCTION ir<0>, ir<1>, vp<[[VP0]]>
; CHECK-NEXT:      EMIT vp<%active.lane.mask> = active lane mask ir<%ix.024>, ir<1024>, ir<1>
; CHECK-NEXT:    Successor(s): vector.body.split
; CHECK-EMPTY:
; CHECK-NEXT:    vector.body.split:
; CHECK-NEXT:      WIDEN ir<%cmp1> = icmp ugt ir<%ix.024>, ir<%conv>
; CHECK-NEXT:    Successor(s): if.then
; CHECK-EMPTY:
; CHECK-NEXT:    if.then:
; CHECK-NEXT:      EMIT vp<[[VP5:%[0-9]+]]> = logical-and vp<%active.lane.mask>, ir<%cmp1>
; CHECK-NEXT:      CLONE ir<%mul> = shl ir<%ix.024>, ir<1>
; CHECK-NEXT:      CLONE ir<%arrayidx> = getelementptr ir<%p>, ir<%mul>
; CHECK-NEXT:      INTERLEAVE-GROUP with factor 2 at %0, ir<%arrayidx>, vp<[[VP5]]>
; CHECK-NEXT:        ir<%0> = load from index 0
; CHECK-NEXT:        ir<%1> = load from index 1
; CHECK-NEXT:      CLONE ir<%add> = or disjoint ir<%mul>, ir<1>
; CHECK-NEXT:      CLONE ir<%arrayidx4> = getelementptr inbounds ir<%p>, ir<%add>
; CHECK-NEXT:      WIDEN ir<%cmp.i> = icmp slt ir<%0>, ir<%1>
; CHECK-NEXT:      WIDEN ir<%spec.select.i> = select ir<%cmp.i>, ir<%1>, ir<%0>
; CHECK-NEXT:      CLONE ir<%arrayidx6> = getelementptr ir<%q>, ir<%mul>
; CHECK-NEXT:      WIDEN ir<%sub> = sub ir<0>, ir<%spec.select.i>
; CHECK-NEXT:      CLONE ir<%arrayidx11> = getelementptr inbounds ir<%q>, ir<%add>
; CHECK-NEXT:      INTERLEAVE-GROUP with factor 2 at <badref>, ir<%arrayidx6>, vp<[[VP5]]>
; CHECK-NEXT:        store ir<%spec.select.i> to index 0
; CHECK-NEXT:        store ir<%sub> to index 1
; CHECK-NEXT:    Successor(s): for.inc
; CHECK-EMPTY:
; CHECK-NEXT:    for.inc:
; CHECK-NEXT:      WIDEN ir<%inc> = add nuw nsw ir<%ix.024>, ir<1>
; CHECK-NEXT:      CLONE ir<%exitcond> = icmp eq ir<%inc>, ir<1024>
; CHECK-NEXT:    Successor(s): vector.latch
; CHECK-EMPTY:
; CHECK-NEXT:    vector.latch:
; CHECK-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP4]]>, vp<[[VP1]]>
; CHECK-NEXT:      EMIT branch-on-count vp<%index.next>, vp<[[VP2]]>
; CHECK-NEXT:    No successors
; CHECK-NEXT:  }
; CHECK-NEXT:  Successor(s): middle.block
; CHECK-EMPTY:
; CHECK-NEXT:  middle.block:
; CHECK-NEXT:  Successor(s): ir-bb<for.end>
; CHECK-EMPTY:
; CHECK-NEXT:  ir-bb<for.end>:
; CHECK-NEXT:  No successors
; CHECK-EMPTY:
; CHECK-NEXT:  scalar.ph:
; CHECK-NEXT:    EMIT-SCALAR vp<%bc.resume.val> = phi [ ir<0>, ir-bb<entry> ]
; CHECK-NEXT:  Successor(s): ir-bb<for.body>
; CHECK-EMPTY:
; CHECK-NEXT:  ir-bb<for.body>:
; CHECK-NEXT:    IR   %ix.024 = phi i32 [ 0, %entry ], [ %inc, %for.inc ] (extra operand: vp<%bc.resume.val> from scalar.ph)
; CHECK-NEXT:    IR   %cmp1 = icmp ugt i32 %ix.024, %conv
; CHECK-NEXT:  No successors
; CHECK-NEXT:  }
;
entry:
  %conv = zext i8 %guard to i32
  br label %for.body

for.body:
  %ix.024 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  %cmp1 = icmp ugt i32 %ix.024, %conv
  br i1 %cmp1, label %if.then, label %for.inc

if.then:
  %mul = shl nuw nsw i32 %ix.024, 1
  %arrayidx = getelementptr inbounds i8, ptr %p, i32 %mul
  %0 = load i8, ptr %arrayidx, align 1
  %add = or disjoint i32 %mul, 1
  %arrayidx4 = getelementptr inbounds i8, ptr %p, i32 %add
  %1 = load i8, ptr %arrayidx4, align 1
  %cmp.i = icmp slt i8 %0, %1
  %spec.select.i = select i1 %cmp.i, i8 %1, i8 %0
  %arrayidx6 = getelementptr inbounds i8, ptr %q, i32 %mul
  store i8 %spec.select.i, ptr %arrayidx6, align 1
  %sub = sub i8 0, %spec.select.i
  %arrayidx11 = getelementptr inbounds i8, ptr %q, i32 %add
  store i8 %sub, ptr %arrayidx11, align 1
  br label %for.inc

for.inc:
  %inc = add nuw nsw i32 %ix.024, 1
  %exitcond = icmp eq i32 %inc, 1024
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}
