; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32
; RUN: llc -mtriple=riscv64 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV64

; Test load-from-store promotion: same size load/store
define i32 @test_load_from_store_same_size(ptr %ptr, i32 %val) {
; RV32-LABEL: test_load_from_store_same_size:
; RV32:       # %bb.0:
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: test_load_from_store_same_size:
; RV64:       # %bb.0:
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  %loaded = load i32, ptr %ptr, align 4
  ret i32 %loaded
}

; Test load-from-store promotion: load from zero store
define i32 @test_load_from_zero_store(ptr %ptr) {
; RV32-LABEL: test_load_from_zero_store:
; RV32:       # %bb.0:
; RV32-NEXT:    sw zero, 0(a0)
; RV32-NEXT:    li a0, 0
; RV32-NEXT:    ret
;
; RV64-LABEL: test_load_from_zero_store:
; RV64:       # %bb.0:
; RV64-NEXT:    sw zero, 0(a0)
; RV64-NEXT:    li a0, 0
; RV64-NEXT:    ret
  store i32 0, ptr %ptr, align 4
  %val = load i32, ptr %ptr, align 4
  ret i32 %val
}

; Test load-from-store promotion: byte load from word store (unsigned)
define i32 @test_load_byte_from_word_store(ptr %ptr, i32 %val) {
; RV32-LABEL: test_load_byte_from_word_store:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a2, a1
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_load_byte_from_word_store:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a2, a1
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  %val_byte = load i8, ptr %ptr, align 1
  %val_ext = zext i8 %val_byte to i32
  ret i32 %val_ext
}

; Test load-from-store promotion: half load from word store (unsigned)
define i32 @test_load_half_from_word_store(ptr %ptr, i32 %val) {
; RV32-LABEL: test_load_half_from_word_store:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a2, a1, 16
; RV32-NEXT:    srli a2, a2, 16
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_load_half_from_word_store:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a2, a1, 48
; RV64-NEXT:    srli a2, a2, 48
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  %val_half = load i16, ptr %ptr, align 2
  %val_ext = zext i16 %val_half to i32
  ret i32 %val_ext
}

; Test that volatile loads are NOT promoted
define i32 @test_volatile_load_no_promote(ptr %ptr, i32 %val) {
; RV32-LABEL: test_volatile_load_no_promote:
; RV32:       # %bb.0:
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_volatile_load_no_promote:
; RV64:       # %bb.0:
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  %loaded = load volatile i32, ptr %ptr, align 4
  ret i32 %loaded
}

; Test that intervening store prevents promotion
define i32 @test_intervening_store_no_promote(ptr %ptr, i32 %val1, i32 %val2) {
; RV32-LABEL: test_intervening_store_no_promote:
; RV32:       # %bb.0:
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_intervening_store_no_promote:
; RV64:       # %bb.0:
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  store i32 %val1, ptr %ptr, align 4
  store i32 %val2, ptr %ptr, align 4
  %loaded = load i32, ptr %ptr, align 4
  ret i32 %loaded
}

; Test promotion with different base address (no promotion)
define i32 @test_different_address_no_promote(ptr %ptr1, ptr %ptr2, i32 %val) {
; RV32-LABEL: test_different_address_no_promote:
; RV32:       # %bb.0:
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_different_address_no_promote:
; RV64:       # %bb.0:
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    lw a0, 0(a1)
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr1, align 4
  %loaded = load i32, ptr %ptr2, align 4
  ret i32 %loaded
}

; Test sign-extending byte load from word store
define i32 @test_load_byte_sext_from_word_store(ptr %ptr, i32 %val) {
; RV32-LABEL: test_load_byte_sext_from_word_store:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a2, a1, 24
; RV32-NEXT:    srai a2, a2, 24
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_load_byte_sext_from_word_store:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a2, a1, 56
; RV64-NEXT:    srai a2, a2, 56
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  %val_byte = load i8, ptr %ptr, align 1
  %val_ext = sext i8 %val_byte to i32
  ret i32 %val_ext
}

; Test that load after call is not promoted (call might modify memory)
define i32 @test_call_prevents_promotion(ptr %ptr, i32 %val) {
; RV32-LABEL: test_call_prevents_promotion:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    sw s0, 8(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32-NEXT:    .cfi_offset ra, -4
; RV32-NEXT:    .cfi_offset s0, -8
; RV32-NEXT:    mv s0, a0
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    call bar
; RV32-NEXT:    lw a0, 0(s0)
; RV32-NEXT:    lw s0, 8(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; RV32-NEXT:    .cfi_restore ra
; RV32-NEXT:    .cfi_restore s0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: test_call_prevents_promotion:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -8
; RV64-NEXT:    .cfi_offset s0, -16
; RV64-NEXT:    mv s0, a0
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    call bar
; RV64-NEXT:    lw a0, 0(s0)
; RV64-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64-NEXT:    .cfi_restore ra
; RV64-NEXT:    .cfi_restore s0
; RV64-NEXT:    addi sp, sp, 16
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
  store i32 %val, ptr %ptr, align 4
  call void @bar()
  %loaded = load i32, ptr %ptr, align 4
  ret i32 %loaded
}

declare void @bar()
