; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32
; RUN: llc -mtriple=riscv64 -mattr=+Xmipslsp -use-riscv-mips-load-store-pairs=1 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV64

; Test zero store merging optimization: sb + sb -> sh
define void @test_zero_store_merge_byte(ptr %ptr) {
; RV32-LABEL: test_zero_store_merge_byte:
; RV32:       # %bb.0:
; RV32-NEXT:    sh zero, 0(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_zero_store_merge_byte:
; RV64:       # %bb.0:
; RV64-NEXT:    sh zero, 0(a0)
; RV64-NEXT:    ret
  store i8 0, ptr %ptr, align 1
  %ptr1 = getelementptr inbounds i8, ptr %ptr, i64 1
  store i8 0, ptr %ptr1, align 1
  ret void
}

; Test zero store merging optimization: sh + sh -> sw
define void @test_zero_store_merge_half(ptr %ptr) {
; RV32-LABEL: test_zero_store_merge_half:
; RV32:       # %bb.0:
; RV32-NEXT:    sw zero, 0(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_zero_store_merge_half:
; RV64:       # %bb.0:
; RV64-NEXT:    sw zero, 0(a0)
; RV64-NEXT:    ret
  store i16 0, ptr %ptr, align 2
  %ptr1 = getelementptr inbounds i16, ptr %ptr, i64 1
  store i16 0, ptr %ptr1, align 2
  ret void
}

; Test zero store merging optimization: sw + sw -> sd (RV64 only)
define void @test_zero_store_merge_word(ptr %ptr) {
; RV32-LABEL: test_zero_store_merge_word:
; RV32:       # %bb.0:
; RV32-NEXT:    sw zero, 0(a0)
; RV32-NEXT:    sw zero, 4(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_zero_store_merge_word:
; RV64:       # %bb.0:
; RV64-NEXT:    sd zero, 0(a0)
; RV64-NEXT:    ret
  store i32 0, ptr %ptr, align 4
  %ptr1 = getelementptr inbounds i32, ptr %ptr, i64 1
  store i32 0, ptr %ptr1, align 4
  ret void
}

; Test that non-adjacent stores are NOT merged
define void @test_zero_store_no_merge_non_adjacent(ptr %ptr) {
; RV32-LABEL: test_zero_store_no_merge_non_adjacent:
; RV32:       # %bb.0:
; RV32-NEXT:    sb zero, 0(a0)
; RV32-NEXT:    sb zero, 2(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_zero_store_no_merge_non_adjacent:
; RV64:       # %bb.0:
; RV64-NEXT:    sb zero, 0(a0)
; RV64-NEXT:    sb zero, 2(a0)
; RV64-NEXT:    ret
  store i8 0, ptr %ptr, align 1
  %ptr2 = getelementptr inbounds i8, ptr %ptr, i64 2
  store i8 0, ptr %ptr2, align 1
  ret void
}

; Test that non-zero stores are NOT merged by this optimization
define void @test_nonzero_store_no_merge(ptr %ptr) {
; RV32-LABEL: test_nonzero_store_no_merge:
; RV32:       # %bb.0:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    sb a1, 0(a0)
; RV32-NEXT:    sb a1, 1(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_nonzero_store_no_merge:
; RV64:       # %bb.0:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    sb a1, 0(a0)
; RV64-NEXT:    sb a1, 1(a0)
; RV64-NEXT:    ret
  store i8 1, ptr %ptr, align 1
  %ptr1 = getelementptr inbounds i8, ptr %ptr, i64 1
  store i8 1, ptr %ptr1, align 1
  ret void
}

; Test that volatile stores are NOT merged
define void @test_volatile_zero_store_no_merge(ptr %ptr) {
; RV32-LABEL: test_volatile_zero_store_no_merge:
; RV32:       # %bb.0:
; RV32-NEXT:    sb zero, 0(a0)
; RV32-NEXT:    sb zero, 1(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_volatile_zero_store_no_merge:
; RV64:       # %bb.0:
; RV64-NEXT:    sb zero, 0(a0)
; RV64-NEXT:    sb zero, 1(a0)
; RV64-NEXT:    ret
  store volatile i8 0, ptr %ptr, align 1
  %ptr1 = getelementptr inbounds i8, ptr %ptr, i64 1
  store volatile i8 0, ptr %ptr1, align 1
  ret void
}

; Test merging three consecutive zero stores (should merge first two)
define void @test_zero_store_merge_three(ptr %ptr) {
; RV32-LABEL: test_zero_store_merge_three:
; RV32:       # %bb.0:
; RV32-NEXT:    sh zero, 0(a0)
; RV32-NEXT:    sb zero, 2(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_zero_store_merge_three:
; RV64:       # %bb.0:
; RV64-NEXT:    sh zero, 0(a0)
; RV64-NEXT:    sb zero, 2(a0)
; RV64-NEXT:    ret
  store i8 0, ptr %ptr, align 1
  %ptr1 = getelementptr inbounds i8, ptr %ptr, i64 1
  store i8 0, ptr %ptr1, align 1
  %ptr2 = getelementptr inbounds i8, ptr %ptr, i64 2
  store i8 0, ptr %ptr2, align 1
  ret void
}
