; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -verify-machineinstrs -mtriple=aarch64-none-linux-gnu -mattr=+neon | FileCheck %s

; Test: Load a byte and broadcast to 8 bytes using multiply by 0x0101010101010101
; Current: ldrb + mov + mul + str (scalar)
; Optimized: ld1r + str (NEON - even better!)
define void @broadcast_byte_to_8bytes(i8* %dst, i8* %src) {
; CHECK-LABEL: broadcast_byte_to_8bytes
; CHECK:       ld1r { v0.8b }, [x1]
; CHECK-NEXT:  str d0, [x0]
; CHECK-NEXT:  ret
  %val = load i8, i8* %src
  %ext = zext i8 %val to i64
  %broadcast = mul i64 %ext, 72340172838076673  ; 0x0101010101010101
  store i64 %broadcast, i64* %dst
  ret void
}

; Test: Load a byte and broadcast to 4 bytes
define void @broadcast_byte_to_4bytes(i8* %dst, i8* %src) {
; CHECK-LABEL: broadcast_byte_to_4bytes
; CHECK:       ld1r { v0.8b }, [x1]
; CHECK-NEXT:  str s0, [x0]
; CHECK-NEXT:  ret
  %val = load i8, i8* %src
  %ext = zext i8 %val to i32
  %broadcast = mul i32 %ext, 16843009  ; 0x01010101
  store i32 %broadcast, i32* %dst
  ret void
}

; Test: Load with negative offset
define void @broadcast_with_negative_offset(i8* %dst, i8* %src) {
; CHECK-LABEL: broadcast_with_negative_offset
; CHECK:       sub x8, x1, #1
; CHECK-NEXT:  ld1r { v0.8b }, [x8]
; CHECK-NEXT:  str d0, [x0]
; CHECK-NEXT:  ret
  %offset.ptr = getelementptr i8, i8* %src, i64 -1
  %val = load i8, i8* %offset.ptr
  %ext = zext i8 %val to i64
  %broadcast = mul i64 %ext, 72340172838076673  ; 0x0101010101010101
  store i64 %broadcast, i64* %dst
  ret void
}
