; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve2p3 < %s | FileCheck %s --check-prefix=SVE2P3
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve,+sme2p3 < %s | FileCheck %s --check-prefix=SME2P3
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sme2p3 -force-streaming < %s | FileCheck %s --check-prefix=STR
;
; FCVTZSN
;

define <vscale x 16 x i8> @fcvtzsn_i8_f16(<vscale x 8 x half> %zn1, <vscale x 8 x half> %zn2) {
; SVE2P3-LABEL: fcvtzsn_i8_f16:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzsn z0.b, { z0.h, z1.h }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzsn_i8_f16:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzsn z0.b, { z0.h, z1.h }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzsn_i8_f16:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzsn z0.b, { z0.h, z1.h }
; STR-NEXT:    ret
  %res = call <vscale x 16 x i8> @llvm.aarch64.sve.fcvtzsn.i8f16(<vscale x 8 x half> %zn1, <vscale x 8 x half> %zn2)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @fcvtzsn_i16_f32(<vscale x 4 x float> %zn1, <vscale x 4 x float> %zn2) {
; SVE2P3-LABEL: fcvtzsn_i16_f32:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzsn z0.h, { z0.s, z1.s }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzsn_i16_f32:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzsn z0.h, { z0.s, z1.s }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzsn_i16_f32:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzsn z0.h, { z0.s, z1.s }
; STR-NEXT:    ret
  %res = call <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzsn.i16f32(<vscale x 4 x float> %zn1, <vscale x 4 x float> %zn2)
  ret <vscale x 8 x i16> %res
}

define <vscale x 4 x i32> @fcvtzsn_i32_f64(<vscale x 2 x double> %zn1, <vscale x 2 x double> %zn2) {
; SVE2P3-LABEL: fcvtzsn_i32_f64:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzsn z0.s, { z0.d, z1.d }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzsn_i32_f64:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzsn z0.s, { z0.d, z1.d }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzsn_i32_f64:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzsn z0.s, { z0.d, z1.d }
; STR-NEXT:    ret
  %res = call <vscale x 4 x i32> @llvm.aarch64.sve.fcvtzsn.i32f64(<vscale x 2 x double> %zn1, <vscale x 2 x double> %zn2)
  ret <vscale x 4 x i32> %res
}

;
; FCVTZUN
;

define <vscale x 16 x i8> @fcvtzun_i8_f16(<vscale x 8 x half> %zn1, <vscale x 8 x half> %zn2) {
; SVE2P3-LABEL: fcvtzun_i8_f16:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzun z0.b, { z0.h, z1.h }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzun_i8_f16:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzun z0.b, { z0.h, z1.h }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzun_i8_f16:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzun z0.b, { z0.h, z1.h }
; STR-NEXT:    ret
  %res = call <vscale x 16 x i8> @llvm.aarch64.sve.fcvtzun.i8f16(<vscale x 8 x half> %zn1, <vscale x 8 x half> %zn2)
  ret <vscale x 16 x i8> %res
}

define <vscale x 8 x i16> @fcvtzun_i16_f32(<vscale x 4 x float> %zn1, <vscale x 4 x float> %zn2) {
; SVE2P3-LABEL: fcvtzun_i16_f32:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzun z0.h, { z0.s, z1.s }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzun_i16_f32:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzun z0.h, { z0.s, z1.s }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzun_i16_f32:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzun z0.h, { z0.s, z1.s }
; STR-NEXT:    ret
  %res = call <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzun.i16f32(<vscale x 4 x float> %zn1, <vscale x 4 x float> %zn2)
  ret <vscale x 8 x i16> %res
}

define <vscale x 4 x i32> @fcvtzun_i32_f64(<vscale x 2 x double> %zn1, <vscale x 2 x double> %zn2) {
; SVE2P3-LABEL: fcvtzun_i32_f64:
; SVE2P3:       // %bb.0:
; SVE2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SVE2P3-NEXT:    fcvtzun z0.s, { z0.d, z1.d }
; SVE2P3-NEXT:    ret
;
; SME2P3-LABEL: fcvtzun_i32_f64:
; SME2P3:       // %bb.0:
; SME2P3-NEXT:    // kill: def $z1 killed $z1 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    // kill: def $z0 killed $z0 killed $z0_z1 def $z0_z1
; SME2P3-NEXT:    fcvtzun z0.s, { z0.d, z1.d }
; SME2P3-NEXT:    ret
;
; STR-LABEL: fcvtzun_i32_f64:
; STR:       // %bb.0:
; STR-NEXT:    fcvtzun z0.s, { z0.d, z1.d }
; STR-NEXT:    ret
  %res = call <vscale x 4 x i32> @llvm.aarch64.sve.fcvtzun.i32f64(<vscale x 2 x double> %zn1, <vscale x 2 x double> %zn2)
  ret <vscale x 4 x i32> %res
}

declare <vscale x 16 x i8> @llvm.aarch64.sve.fcvtzsn.i8f16(<vscale x 8 x half>, <vscale x 8 x half>)
declare <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzsn.i16f32(<vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.fcvtzsn.i32f64(<vscale x 2 x double>, <vscale x 2 x double>)

declare <vscale x 16 x i8> @llvm.aarch64.sve.fcvtzun.i8f16(<vscale x 8 x half>, <vscale x 8 x half>)
declare <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzun.i16f32(<vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.fcvtzun.i32f64(<vscale x 2 x double>, <vscale x 2 x double>)
