; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i1)
declare void @usef64(double)

; X == 42.0 ? X : 42.0 --> 42.0

define double @oeq(double %x) {
; CHECK-LABEL: @oeq(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[X:%.*]], 4.200000e+01
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    ret double 4.200000e+01
;
  %cmp = fcmp oeq double %x, 42.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double %x, double 42.0
  ret double %cond
}

; X == 42.0 ? 42.0 : X --> X

define float @oeq_swapped(float %x) {
; CHECK-LABEL: @oeq_swapped(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[X:%.*]], 4.200000e+01
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    ret float [[X]]
;
  %cmp = fcmp oeq float %x, 42.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, float 42.0, float %x
  ret float %cond
}

; x != y ? x : y -> x if it's the right kind of != and at least
; one of x and y is not negative zero.

; X != 42.0 ? X : 42.0 --> X

define double @une(double %x) {
; CHECK-LABEL: @une(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp une double [[X:%.*]], 4.200000e+01
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    ret double [[X]]
;
  %cmp = fcmp une double %x, 42.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double %x, double 42.0
  ret double %cond
}

; X != 42.0 ? 42.0 : X --> 42.0

define double @une_swapped(double %x) {
; CHECK-LABEL: @une_swapped(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp une double [[X:%.*]], 4.200000e+01
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    ret double 4.200000e+01
;
  %cmp = fcmp une double %x, 42.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double 42.0, double %x
  ret double %cond
}

define double @une_could_be_negzero(double %x, double %y) {
; CHECK-LABEL: @une_could_be_negzero(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp une double [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP]], double [[X]], double [[Y]]
; CHECK-NEXT:    ret double [[COND]]
;
  %cmp = fcmp une double %x, %y
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double %x, double %y
  ret double %cond
}

define double @une_swapped_could_be_negzero(double %x, double %y) {
; CHECK-LABEL: @une_swapped_could_be_negzero(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp une double [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP]], double [[Y]], double [[X]]
; CHECK-NEXT:    ret double [[COND]]
;
  %cmp = fcmp une double %x, %y
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double %y, double %x
  ret double %cond
}

define double @one(double %x) {
; CHECK-LABEL: @one(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp one double [[X:%.*]], -1.000000e+00
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP]], double [[X]], double -1.000000e+00
; CHECK-NEXT:    ret double [[COND]]
;
  %cmp = fcmp one double %x, -1.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double %x, double -1.0
  ret double %cond
}

define double @one_swapped(double %x) {
; CHECK-LABEL: @one_swapped(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp one double [[X:%.*]], -1.000000e+00
; CHECK-NEXT:    call void @use(i1 [[CMP]])
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP]], double -1.000000e+00, double [[X]]
; CHECK-NEXT:    ret double [[COND]]
;
  %cmp = fcmp one double %x, -1.0
  call void @use(i1 %cmp)      ; extra use to thwart predicate canonicalization
  %cond = select i1 %cmp, double -1.0, double %x
  ret double %cond
}

define i1 @fcmp_oeq_select(i1 %cond, float %a, float %b) {
; CHECK-LABEL: @fcmp_oeq_select(
; CHECK-NEXT:    [[RES:%.*]] = fcmp oeq float [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret i1 [[RES]]
;
  %lhs = select i1 %cond, float %a, float %b
  %rhs = select i1 %cond, float %b, float %a
  %res = fcmp oeq float %lhs, %rhs
  ret i1 %res
}

define i1 @fcmp_uno_select(i1 %cond, float %a, float %b) {
; CHECK-LABEL: @fcmp_uno_select(
; CHECK-NEXT:    [[RES:%.*]] = fcmp uno float [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    ret i1 [[RES]]
;
  %lhs = select i1 %cond, float %a, float %b
  %rhs = select i1 %cond, float %b, float %a
  %res = fcmp uno float %lhs, %rhs
  ret i1 %res
}

define i1 @fcmp_ogt_select(i1 %cond, float %a, float %b) {
; CHECK-LABEL: @fcmp_ogt_select(
; CHECK-NEXT:    [[LHS:%.*]] = select i1 [[COND:%.*]], float [[A:%.*]], float [[B:%.*]]
; CHECK-NEXT:    [[RHS:%.*]] = select i1 [[COND]], float [[B]], float [[A]]
; CHECK-NEXT:    [[RES:%.*]] = fcmp ogt float [[LHS]], [[RHS]]
; CHECK-NEXT:    ret i1 [[RES]]
;
  %lhs = select i1 %cond, float %a, float %b
  %rhs = select i1 %cond, float %b, float %a
  %res = fcmp ogt float %lhs, %rhs
  ret i1 %res
}

define i1 @test_fcmp_select_const_const(double %x) {
; CHECK-LABEL: @test_fcmp_select_const_const(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp uno double [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    ret i1 [[CMP1]]
;
  %cmp1 = fcmp ord double %x, 0.000000e+00
  %sel = select i1 %cmp1, double 0xFFFFFFFFFFFFFFFF, double 0.000000e+00
  %cmp2 = fcmp oeq double %sel, 0.000000e+00
  ret i1 %cmp2
}

define i1 @test_fcmp_select_var_const(double %x, double %y) {
; CHECK-LABEL: @test_fcmp_select_var_const(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ule double [[X:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp olt double [[Y:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[CMP2:%.*]] = select i1 [[CMP1]], i1 true, i1 [[TMP1]]
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt double %x, 0x3E80000000000000
  %sel = select i1 %cmp1, double %y, double 0.000000e+00
  %cmp2 = fcmp olt double %sel, 0x3E80000000000000
  ret i1 %cmp2
}

define i1 @test_fcmp_select_var_const_fmf(double %x, double %y) {
; CHECK-LABEL: @test_fcmp_select_var_const_fmf(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ule double [[X:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp nnan olt double [[Y:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[CMP2:%.*]] = select i1 [[CMP1]], i1 true, i1 [[TMP1]]
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ogt double %x, 0x3E80000000000000
  %sel = select i1 %cmp1, double %y, double 0.000000e+00
  %cmp2 = fcmp nnan olt double %sel, 0x3E80000000000000
  ret i1 %cmp2
}

define <2 x i1> @test_fcmp_select_const_const_vec(<2 x double> %x) {
; CHECK-LABEL: @test_fcmp_select_const_const_vec(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp uno <2 x double> [[X:%.*]], zeroinitializer
; CHECK-NEXT:    ret <2 x i1> [[CMP1]]
;
  %cmp1 = fcmp ord <2 x double> %x, zeroinitializer
  %sel = select <2 x i1> %cmp1, <2 x double> <double 0xFFFFFFFFFFFFFFFF, double 0xFFFFFFFFFFFFFFFF>, <2 x double> zeroinitializer
  %cmp2 = fcmp oeq <2 x double> %sel, zeroinitializer
  ret <2 x i1> %cmp2
}

; Don't break clamp idioms

define double @test_fcmp_select_clamp(double %x) {
; CHECK-LABEL: @test_fcmp_select_clamp(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ogt double [[X:%.*]], 9.000000e-01
; CHECK-NEXT:    [[SEL1:%.*]] = select i1 [[CMP1]], double 9.000000e-01, double [[X]]
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp olt double [[SEL1]], 5.000000e-01
; CHECK-NEXT:    [[SEL2:%.*]] = select i1 [[CMP2]], double 5.000000e-01, double [[SEL1]]
; CHECK-NEXT:    ret double [[SEL2]]
;
  %cmp1 = fcmp ogt double %x, 9.000000e-01
  %sel1 = select i1 %cmp1, double 9.000000e-01, double %x
  %cmp2 = fcmp olt double %sel1, 5.000000e-01
  %sel2 = select i1 %cmp2, double 5.000000e-01, double %sel1
  ret double %sel2
}

; Don't break fmin/fmax idioms

define double @test_fcmp_select_maxnum(double %x) {
; CHECK-LABEL: @test_fcmp_select_maxnum(
; CHECK-NEXT:    [[SEL1:%.*]] = call nnan nsz double @llvm.maxnum.f64(double [[X:%.*]], double 1.000000e+00)
; CHECK-NEXT:    [[SEL2:%.*]] = call nnan nsz double @llvm.minnum.f64(double [[SEL1]], double 2.550000e+02)
; CHECK-NEXT:    ret double [[SEL2]]
;
  %cmp1 = fcmp nnan ogt double %x, 1.0
  %sel1 = select nsz i1 %cmp1, double %x, double 1.0
  %cmp2 = fcmp nnan olt double %sel1, 255.0
  %sel2 = select nsz i1 %cmp2, double %sel1, double 255.0
  ret double %sel2
}

define i1 @test_fcmp_select_const_const_multiuse(double %x) {
; CHECK-LABEL: @test_fcmp_select_const_const_multiuse(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ord double [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP1]], double 0xFFFFFFFFFFFFFFFF, double 0.000000e+00
; CHECK-NEXT:    call void @usef64(double [[SEL]])
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp oeq double [[SEL]], 0.000000e+00
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ord double %x, 0.000000e+00
  %sel = select i1 %cmp1, double 0xFFFFFFFFFFFFFFFF, double 0.000000e+00
  call void @usef64(double %sel)
  %cmp2 = fcmp oeq double %sel, 0.000000e+00
  ret i1 %cmp2
}

define i1 @test_fcmp_select_const_const_unordered(double %x) {
; CHECK-LABEL: @test_fcmp_select_const_const_unordered(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ord double [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    ret i1 [[CMP1]]
;
  %cmp1 = fcmp uno double %x, 0.000000e+00
  %sel = select i1 %cmp1, double 0xFFFFFFFFFFFFFFFF, double 0.000000e+00
  %cmp2 = fcmp oeq double %sel, 0.000000e+00
  ret i1 %cmp2
}

define i1 @test_fcmp_select_var_const_unordered(double %x, double %y) {
; CHECK-LABEL: @test_fcmp_select_var_const_unordered(
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp ult double [[X:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ugt double [[Y:%.*]], 0x3E80000000000000
; CHECK-NEXT:    [[CMP2:%.*]] = select i1 [[CMP1]], i1 [[TMP1]], i1 false
; CHECK-NEXT:    ret i1 [[CMP2]]
;
  %cmp1 = fcmp ult double %x, 0x3E80000000000000
  %sel = select i1 %cmp1, double %y, double 0.000000e+00
  %cmp2 = fcmp ugt double %sel, 0x3E80000000000000
  ret i1 %cmp2
}

define i1 @test_fcmp_ord_select_fcmp_oeq_var_const(double %x) {
; CHECK-LABEL: @test_fcmp_ord_select_fcmp_oeq_var_const(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp oeq double [[X:%.*]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[TMP1]]
;
  %cmp1 = fcmp ord double %x, 0.000000e+00
  %sel = select i1 %cmp1, double %x, double 0.000000e+00
  %cmp2 = fcmp oeq double %sel, 1.000000e+00
  ret i1 %cmp2
}

; Make sure that we recognize the SPF correctly.

define float @test_select_nnan_nsz_fcmp_olt(float %x) {
; CHECK-LABEL: @test_select_nnan_nsz_fcmp_olt(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp olt float [[X:%.*]], -0.000000e+00
; CHECK-NEXT:    [[SEL1:%.*]] = select i1 [[TMP1]], float [[X]], float -0.000000e+00
; CHECK-NEXT:    ret float [[SEL1]]
;
  %cmp = fcmp olt float %x, 0.000000e+00
  %sel = select nnan nsz i1 %cmp, float %x, float -0.000000e+00
  ret float %sel
}

define float @test_select_nnan_nsz_fcmp_ult(float %x) {
; CHECK-LABEL: @test_select_nnan_nsz_fcmp_ult(
; CHECK-NEXT:    [[DOTINV:%.*]] = fcmp oge float [[X:%.*]], 0.000000e+00
; CHECK-NEXT:    [[SEL1:%.*]] = select i1 [[DOTINV]], float -0.000000e+00, float [[X]]
; CHECK-NEXT:    ret float [[SEL1]]
;
  %cmp = fcmp ult float %x, 0.000000e+00
  %sel = select nnan nsz i1 %cmp, float %x, float -0.000000e+00
  ret float %sel
}

define float @test_select_fcmp_sitofp_max(i8 %x) {
; CHECK-LABEL: @test_select_fcmp_sitofp_max(
; CHECK-NEXT:    [[F:%.*]] = sitofp i8 [[X:%.*]] to float
; CHECK-NEXT:    ret float [[F]]
;
  %f = sitofp i8 %x to float
  %cmp = fcmp ole float %f, -1.280000e+02
  %sel = select i1 %cmp, float -1.280000e+02, float %f
  ret float %sel
}

define <2 x float> @test_select_fcmp_sitofp_max_vec(<2 x i8> %x) {
; CHECK-LABEL: @test_select_fcmp_sitofp_max_vec(
; CHECK-NEXT:    [[F:%.*]] = sitofp <2 x i8> [[X:%.*]] to <2 x float>
; CHECK-NEXT:    ret <2 x float> [[F]]
;
  %f = sitofp <2 x i8> %x to <2 x float>
  %cmp = fcmp ole <2 x float> %f, splat (float -1.280000e+02)
  %sel = select <2 x i1> %cmp, <2 x float> splat (float -1.280000e+02), <2 x float> %f
  ret <2 x float> %sel
}

define float @test_select_fcmp_sitofp_min(i8 %x) {
; CHECK-LABEL: @test_select_fcmp_sitofp_min(
; CHECK-NEXT:    [[F:%.*]] = sitofp i8 [[X:%.*]] to float
; CHECK-NEXT:    ret float [[F]]
;
  %f = sitofp i8 %x to float
  %cmp = fcmp oge float %f, 1.270000e+02
  %sel = select i1 %cmp, float 1.270000e+02, float %f
  ret float %sel
}

define float @test_select_fcmp_uitofp_min(i8 %x) {
; CHECK-LABEL: @test_select_fcmp_uitofp_min(
; CHECK-NEXT:    [[F:%.*]] = uitofp i8 [[X:%.*]] to float
; CHECK-NEXT:    ret float [[F]]
;
  %f = uitofp i8 %x to float
  %cmp = fcmp oge float %f, 2.550000e+02
  %sel = select i1 %cmp, float 2.550000e+02, float %f
  ret float %sel
}

define i1 @fold_fcmp_clamp_oeq_hi(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_oeq_hi(
; CHECK-NEXT:    [[CMP:%.*]] =  
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 5.0
  %min = select i1 %min_cmp, double 5.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp oeq double %clamp, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_ueq_hi(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_ueq_hi(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oge double [[X:%.*]], 1.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 1.0
  %min = select i1 %min_cmp, double 1.0, double %x
  %max_cmp = fcmp ogt double %min, 0.0
  %clamp = select i1 %max_cmp, double %min, double 0.0
  %cmp = fcmp ueq double %clamp, 1.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_oeq_lo(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_oeq_lo(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp ule double [[X:%.*]], 2.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 4.0
  %min = select i1 %min_cmp, double 4.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp oeq double %clamp, 2.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_ueq_lo(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_ueq_lo(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp ule double [[X:%.*]], 2.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 5.0
  %min = select i1 %min_cmp, double 5.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp ueq double %clamp, 2.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_minmax_alt_oeq_hi(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_minmax_alt_oeq_hi(
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oge double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  ; clamp as min(max(X, 2), 5) instead of max(min(X, 5), 2) pattern
  %max_cmp = fcmp ogt double %x, 2.0
  %max = select i1 %max_cmp, double %x, double 2.0
  %min_cmp = fcmp ogt double %max, 5.0
  %clamp = select i1 %min_cmp, double 5.0, double %max
  %cmp = fcmp oeq double %clamp, 5.0
  ret i1 %cmp
}

define i1 @fold_two_clamp_hi(float %arg0, float %arg1) {
; CHECK-LABEL: @fold_two_clamp_hi(
; CHECK-NEXT:   [[V8:%.*]] = fcmp oge float [[ARG0:%.*]], 1.000000e+00
; CHECK-NEXT:   [[V9:%.*]] = fcmp oge float [[ARG1:%.*]], 1.000000e+00
; CHECK-NEXT:   [[V10:%.*]] = and i1 [[V8]], [[V9]]
; CHECK-NEXT:  ret i1 [[V10]]
;
  %v0 = fcmp ogt float %arg1, 1.000000e+00
  %v1 = select i1 %v0, float 1.000000e+00, float %arg1
  %v2 = fcmp ogt float %v1, 0.000000e+00
  %v3 = select i1 %v2, float %v1, float 0.000000e+00
  %v4 = fcmp ogt float %arg0, 1.000000e+00
  %v5 = select i1 %v4, float 1.000000e+00, float %arg0
  %v6 = fcmp ogt float %v5, 0.000000e+00
  %v7 = select i1 %v6, float %v5, float 0.000000e+00
  %v8 = fcmp oeq float %v3, 1.000000e+00
  %v9 = fcmp oeq float %v7, 1.000000e+00
  %v10 = and i1 %v8, %v9
  ret i1 %v10
}

; Negative tests

define i1 @fold_fcmp_clamp_oeq_mid(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_oeq_mid(
; CHECK-NEXT:    [[MIN_CMP:%.*]] = fcmp ogt double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[MIN:%.*]] = select i1 [[MIN_CMP]], double 5.000000e+00, double [[X]]
; CHECK-NEXT:    [[MAX_CMP:%.*]] = fcmp ogt double [[MIN]], 2.000000e+00
; CHECK-NEXT:    [[CLAMP:%.*]] = select i1 [[MAX_CMP]], double [[MIN]], double 2.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[CLAMP]], 3.000000e+00
; CHECK-NEXT: ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 5.0
  %min = select i1 %min_cmp, double 5.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp oeq double %clamp, 3.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_non_ogt(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_non_ogt(
; CHECK-NEXT:    [[MIN_CMP:%.*]] = fcmp oge double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[MIN:%.*]] = select i1 [[MIN_CMP]], double 5.000000e+00, double [[X]]
; CHECK-NEXT:    [[MAX_CMP:%.*]] = fcmp ogt double [[MIN]], 2.000000e+00
; CHECK-NEXT:    [[CLAMP:%.*]] = select i1 [[MAX_CMP]], double [[MIN]], double 2.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[CLAMP]], 5.000000e+00
; CHECK-NEXT: ret i1 [[CMP]]
;
  %min_cmp = fcmp oge double %x, 5.0
  %min = select i1 %min_cmp, double 5.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp oeq double %clamp, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_unsupported_pred_one(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_unsupported_pred_one(
; CHECK-NEXT:    [[MIN_CMP:%.*]] = fcmp ogt double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[MIN:%.*]] = select i1 [[MIN_CMP]], double 5.000000e+00, double [[X]]
; CHECK-NEXT:    [[MAX_CMP:%.*]] = fcmp ogt double [[MIN]], 2.000000e+00
; CHECK-NEXT:    [[CLAMP:%.*]] = select i1 [[MAX_CMP]], double [[MIN]], double 2.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp one double [[CLAMP]], 5.000000e+00
; CHECK-NEXT: ret i1 [[CMP]]
;
  %min_cmp = fcmp ogt double %x, 5.0
  %min = select i1 %min_cmp, double 5.0, double %x
  %max_cmp = fcmp ogt double %min, 2.0
  %clamp = select i1 %max_cmp, double %min, double 2.0
  %cmp = fcmp one double %clamp, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_minmin(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_minmin(
; CHECK-NEXT:    [[INNER_CMP:%.*]] = fcmp ogt double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[INNER_MIN:%.*]] = select i1 [[INNER_CMP]], double 5.000000e+00, double [[X]]
; CHECK-NEXT:    [[OUTER_CMP:%.*]] = fcmp ogt double [[INNER_MIN]], 2.000000e+00
; CHECK-NEXT:    [[MINMIN:%.*]] = select i1 [[OUTER_CMP]], double 2.000000e+00, double [[INNER_MIN]]
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[MINMIN]], 5.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  ; Looks like a clamp shape but computes min(min(x, 5), 2).
  %inner_cmp = fcmp ogt double %x, 5.0
  %inner_min = select i1 %inner_cmp, double 5.0, double %x
  %outer_cmp = fcmp ogt double %inner_min, 2.0
  %minmin = select i1 %outer_cmp, double 2.0, double %inner_min
  %cmp = fcmp oeq double %minmin, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_no_clamp(double %x, double %y) {
; CHECK-LABEL: @fold_fcmp_no_clamp(
; CHECK-NEXT:    [[OUTER_CMP:%.*]] = fcmp ogt double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    [[OUTER:%.*]] = select i1 [[OUTER_CMP]], double [[X]], double [[Y:%.*]]
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[OUTER]], 5.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  ; Outer min/max is present but not of the form min/max(inner_select, constant).
  %outer_cmp = fcmp ogt double %x, 5.0
  %outer = select i1 %outer_cmp, double %x, double %y
  %cmp = fcmp oeq double %outer, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_inner_bound_non_constant(double %x, double %b) {
; CHECK-LABEL: @fold_fcmp_clamp_inner_bound_non_constant(
; CHECK-NEXT:    [[INNER_CMP:%.*]] = fcmp ogt double [[X:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[INNER:%.*]] = select i1 [[INNER_CMP]], double [[B]], double [[X]]
; CHECK-NEXT:    [[OUTER_CMP:%.*]] = fcmp ogt double [[INNER]], 2.000000e+00
; CHECK-NEXT:    [[CLAMP:%.*]] = select i1 [[OUTER_CMP]], double [[INNER]], double 2.000000e+00
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq double [[CLAMP]], 2.000000e+00
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %inner_cmp = fcmp ogt double %x, %b
  %inner = select i1 %inner_cmp, double %b, double %x
  %outer_cmp = fcmp ogt double %inner, 2.0
  %clamp = select i1 %outer_cmp, double %inner, double 2.0
  %cmp = fcmp oeq double %clamp, 2.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_inner_both_constants(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_inner_both_constants(
; CHECK-NEXT:    [[INNER_CMP:%.*]] = fcmp ogt double [[X:%.*]], 5.000000e+00
; CHECK-NEXT:    ret i1 [[INNER_CMP]]
;
  %inner_cmp = fcmp ogt double %x, 5.0
  %inner = select i1 %inner_cmp, double 5.0, double 4.0
  %outer_cmp = fcmp ogt double %inner, 2.0
  %clamp = select i1 %outer_cmp, double %inner, double 2.0
  %cmp = fcmp oeq double %clamp, 5.0
  ret i1 %cmp
}

define i1 @fold_fcmp_clamp_equal_bounds(double %x) {
; CHECK-LABEL: @fold_fcmp_clamp_equal_bounds(
; CHECK-NEXT:    ret i1 true
;
  %inner_cmp = fcmp ogt double %x, 2.0
  %inner = select i1 %inner_cmp, double 2.0, double %x
  %outer_cmp = fcmp ogt double %inner, 2.0
  %clamp = select i1 %outer_cmp, double %inner, double 2.0
  %cmp = fcmp oeq double %clamp, 2.0
  ret i1 %cmp
}
