// NOTE: File has been autogenerated by utils/aarch64_builtins_test_generator.py
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sve -target-feature +sve2p3 -verify
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sme2p3 -target-feature +sve -verify
// expected-no-diagnostics

// REQUIRES: aarch64-registered-target

#include <arm_sve.h>

// Properties: guard="sve,(sve2p3|sme2p3)" streaming_guard="sme,(sve2p3|sme2p3)" flags="feature-dependent"

void test(void) {
  svint16x2_t svint16x2_t_val;
  svint32x2_t svint32x2_t_val;
  svuint16x2_t svuint16x2_t_val;
  svuint32x2_t svuint32x2_t_val;

  svqrshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqrshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqrshrn_s8(svint16x2_t_val, 2);
  svqrshrn_u8(svuint16x2_t_val, 2);
  svqrshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqrshrun_u8(svint16x2_t_val, 2);
  svqshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqshrn_n_s16_s32_x2(svint32x2_t_val, 2);
  svqshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqshrn_n_u16_u32_x2(svuint32x2_t_val, 2);
  svqshrn_s8(svint16x2_t_val, 2);
  svqshrn_s16(svint32x2_t_val, 2);
  svqshrn_u8(svuint16x2_t_val, 2);
  svqshrn_u16(svuint32x2_t_val, 2);
  svqshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqshrun_n_u16_s32_x2(svint32x2_t_val, 2);
  svqshrun_u8(svint16x2_t_val, 2);
  svqshrun_u16(svint32x2_t_val, 2);
}

void test_streaming(void) __arm_streaming{
  svint16x2_t svint16x2_t_val;
  svint32x2_t svint32x2_t_val;
  svuint16x2_t svuint16x2_t_val;
  svuint32x2_t svuint32x2_t_val;

  svqrshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqrshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqrshrn_s8(svint16x2_t_val, 2);
  svqrshrn_u8(svuint16x2_t_val, 2);
  svqrshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqrshrun_u8(svint16x2_t_val, 2);
  svqshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqshrn_n_s16_s32_x2(svint32x2_t_val, 2);
  svqshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqshrn_n_u16_u32_x2(svuint32x2_t_val, 2);
  svqshrn_s8(svint16x2_t_val, 2);
  svqshrn_s16(svint32x2_t_val, 2);
  svqshrn_u8(svuint16x2_t_val, 2);
  svqshrn_u16(svuint32x2_t_val, 2);
  svqshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqshrun_n_u16_s32_x2(svint32x2_t_val, 2);
  svqshrun_u8(svint16x2_t_val, 2);
  svqshrun_u16(svint32x2_t_val, 2);
}

void test_streaming_compatible(void) __arm_streaming_compatible{
  svint16x2_t svint16x2_t_val;
  svint32x2_t svint32x2_t_val;
  svuint16x2_t svuint16x2_t_val;
  svuint32x2_t svuint32x2_t_val;

  svqrshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqrshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqrshrn_s8(svint16x2_t_val, 2);
  svqrshrn_u8(svuint16x2_t_val, 2);
  svqrshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqrshrun_u8(svint16x2_t_val, 2);
  svqshrn_n_s8_s16_x2(svint16x2_t_val, 2);
  svqshrn_n_s16_s32_x2(svint32x2_t_val, 2);
  svqshrn_n_u8_u16_x2(svuint16x2_t_val, 2);
  svqshrn_n_u16_u32_x2(svuint32x2_t_val, 2);
  svqshrn_s8(svint16x2_t_val, 2);
  svqshrn_s16(svint32x2_t_val, 2);
  svqshrn_u8(svuint16x2_t_val, 2);
  svqshrn_u16(svuint32x2_t_val, 2);
  svqshrun_n_u8_s16_x2(svint16x2_t_val, 2);
  svqshrun_n_u16_s32_x2(svint32x2_t_val, 2);
  svqshrun_u8(svint16x2_t_val, 2);
  svqshrun_u16(svint32x2_t_val, 2);
}
