// NOTE: File has been autogenerated by utils/aarch64_builtins_test_generator.py
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sve -target-feature +sve2p3 -verify
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sme2p3 -target-feature +sve -verify
// expected-no-diagnostics

// REQUIRES: aarch64-registered-target

#include <arm_sve.h>

// Properties: guard="sve,(sve2p3|sme2p3)" streaming_guard="sme,(sve2p3|sme2p3)" flags="feature-dependent"

void test(void) {
  int8_t int8_t_val;
  int16_t int16_t_val;
  int32_t int32_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svint64_t svint64_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;
  svuint64_t svuint64_t_val;
  uint8_t uint8_t_val;
  uint16_t uint16_t_val;
  uint32_t uint32_t_val;

  svabal(svint16_t_val, svint8_t_val, int8_t_val);
  svabal(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal(svint32_t_val, svint16_t_val, int16_t_val);
  svabal(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal(svint64_t_val, svint32_t_val, int32_t_val);
  svabal(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal(svuint64_t_val, svuint32_t_val, svuint32_t_val);
  svabal(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_n_s16(svint16_t_val, svint8_t_val, int8_t_val);
  svabal_n_s32(svint32_t_val, svint16_t_val, int16_t_val);
  svabal_n_s64(svint64_t_val, svint32_t_val, int32_t_val);
  svabal_n_u16(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal_n_u32(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal_n_u64(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_s16(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal_s32(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal_s64(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal_u16(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal_u32(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal_u64(svuint64_t_val, svuint32_t_val, svuint32_t_val);
}

void test_streaming(void) __arm_streaming{
  int8_t int8_t_val;
  int16_t int16_t_val;
  int32_t int32_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svint64_t svint64_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;
  svuint64_t svuint64_t_val;
  uint8_t uint8_t_val;
  uint16_t uint16_t_val;
  uint32_t uint32_t_val;

  svabal(svint16_t_val, svint8_t_val, int8_t_val);
  svabal(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal(svint32_t_val, svint16_t_val, int16_t_val);
  svabal(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal(svint64_t_val, svint32_t_val, int32_t_val);
  svabal(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal(svuint64_t_val, svuint32_t_val, svuint32_t_val);
  svabal(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_n_s16(svint16_t_val, svint8_t_val, int8_t_val);
  svabal_n_s32(svint32_t_val, svint16_t_val, int16_t_val);
  svabal_n_s64(svint64_t_val, svint32_t_val, int32_t_val);
  svabal_n_u16(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal_n_u32(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal_n_u64(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_s16(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal_s32(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal_s64(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal_u16(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal_u32(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal_u64(svuint64_t_val, svuint32_t_val, svuint32_t_val);
}

void test_streaming_compatible(void) __arm_streaming_compatible{
  int8_t int8_t_val;
  int16_t int16_t_val;
  int32_t int32_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svint64_t svint64_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;
  svuint64_t svuint64_t_val;
  uint8_t uint8_t_val;
  uint16_t uint16_t_val;
  uint32_t uint32_t_val;

  svabal(svint16_t_val, svint8_t_val, int8_t_val);
  svabal(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal(svint32_t_val, svint16_t_val, int16_t_val);
  svabal(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal(svint64_t_val, svint32_t_val, int32_t_val);
  svabal(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal(svuint64_t_val, svuint32_t_val, svuint32_t_val);
  svabal(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_n_s16(svint16_t_val, svint8_t_val, int8_t_val);
  svabal_n_s32(svint32_t_val, svint16_t_val, int16_t_val);
  svabal_n_s64(svint64_t_val, svint32_t_val, int32_t_val);
  svabal_n_u16(svuint16_t_val, svuint8_t_val, uint8_t_val);
  svabal_n_u32(svuint32_t_val, svuint16_t_val, uint16_t_val);
  svabal_n_u64(svuint64_t_val, svuint32_t_val, uint32_t_val);
  svabal_s16(svint16_t_val, svint8_t_val, svint8_t_val);
  svabal_s32(svint32_t_val, svint16_t_val, svint16_t_val);
  svabal_s64(svint64_t_val, svint32_t_val, svint32_t_val);
  svabal_u16(svuint16_t_val, svuint8_t_val, svuint8_t_val);
  svabal_u32(svuint32_t_val, svuint16_t_val, svuint16_t_val);
  svabal_u64(svuint64_t_val, svuint32_t_val, svuint32_t_val);
}
