// NOTE: File has been autogenerated by utils/aarch64_builtins_test_generator.py
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sve -target-feature +sve2p3 -verify
// RUN: %clang_cc1 %s -fsyntax-only -triple aarch64-none-linux-gnu -target-feature +sme -target-feature +sme2p3 -target-feature +sve -verify
// expected-no-diagnostics

// REQUIRES: aarch64-registered-target

#include <arm_sve.h>

// Properties: guard="sve,(sve2p3|sme2p3)" streaming_guard="sme,(sve2p3|sme2p3)" flags="feature-dependent"

void test(void) {
  svfloat16x2_t svfloat16x2_t_val;
  svfloat32x2_t svfloat32x2_t_val;
  svfloat64x2_t svfloat64x2_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;

  svcvt_s8(svfloat16x2_t_val);
  svcvt_s8_f16_x2(svfloat16x2_t_val);
  svcvt_s16(svfloat32x2_t_val);
  svcvt_s16_f32_x2(svfloat32x2_t_val);
  svcvt_s32(svfloat64x2_t_val);
  svcvt_s32_f64_x2(svfloat64x2_t_val);
  svcvt_u8(svfloat16x2_t_val);
  svcvt_u8_f16_x2(svfloat16x2_t_val);
  svcvt_u16(svfloat32x2_t_val);
  svcvt_u16_f32_x2(svfloat32x2_t_val);
  svcvt_u32(svfloat64x2_t_val);
  svcvt_u32_f64_x2(svfloat64x2_t_val);
  svcvtb_f16_s8(svint8_t_val);
  svcvtb_f16_u8(svuint8_t_val);
  svcvtb_f32_s16(svint16_t_val);
  svcvtb_f32_u16(svuint16_t_val);
  svcvtb_f64_s32(svint32_t_val);
  svcvtb_f64_u32(svuint32_t_val);
  svcvtt_f16_s8(svint8_t_val);
  svcvtt_f16_u8(svuint8_t_val);
  svcvtt_f32_s16(svint16_t_val);
  svcvtt_f32_u16(svuint16_t_val);
  svcvtt_f64_s32(svint32_t_val);
  svcvtt_f64_u32(svuint32_t_val);
}

void test_streaming(void) __arm_streaming{
  svfloat16x2_t svfloat16x2_t_val;
  svfloat32x2_t svfloat32x2_t_val;
  svfloat64x2_t svfloat64x2_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;

  svcvt_s8(svfloat16x2_t_val);
  svcvt_s8_f16_x2(svfloat16x2_t_val);
  svcvt_s16(svfloat32x2_t_val);
  svcvt_s16_f32_x2(svfloat32x2_t_val);
  svcvt_s32(svfloat64x2_t_val);
  svcvt_s32_f64_x2(svfloat64x2_t_val);
  svcvt_u8(svfloat16x2_t_val);
  svcvt_u8_f16_x2(svfloat16x2_t_val);
  svcvt_u16(svfloat32x2_t_val);
  svcvt_u16_f32_x2(svfloat32x2_t_val);
  svcvt_u32(svfloat64x2_t_val);
  svcvt_u32_f64_x2(svfloat64x2_t_val);
  svcvtb_f16_s8(svint8_t_val);
  svcvtb_f16_u8(svuint8_t_val);
  svcvtb_f32_s16(svint16_t_val);
  svcvtb_f32_u16(svuint16_t_val);
  svcvtb_f64_s32(svint32_t_val);
  svcvtb_f64_u32(svuint32_t_val);
  svcvtt_f16_s8(svint8_t_val);
  svcvtt_f16_u8(svuint8_t_val);
  svcvtt_f32_s16(svint16_t_val);
  svcvtt_f32_u16(svuint16_t_val);
  svcvtt_f64_s32(svint32_t_val);
  svcvtt_f64_u32(svuint32_t_val);
}

void test_streaming_compatible(void) __arm_streaming_compatible{
  svfloat16x2_t svfloat16x2_t_val;
  svfloat32x2_t svfloat32x2_t_val;
  svfloat64x2_t svfloat64x2_t_val;
  svint8_t svint8_t_val;
  svint16_t svint16_t_val;
  svint32_t svint32_t_val;
  svuint8_t svuint8_t_val;
  svuint16_t svuint16_t_val;
  svuint32_t svuint32_t_val;

  svcvt_s8(svfloat16x2_t_val);
  svcvt_s8_f16_x2(svfloat16x2_t_val);
  svcvt_s16(svfloat32x2_t_val);
  svcvt_s16_f32_x2(svfloat32x2_t_val);
  svcvt_s32(svfloat64x2_t_val);
  svcvt_s32_f64_x2(svfloat64x2_t_val);
  svcvt_u8(svfloat16x2_t_val);
  svcvt_u8_f16_x2(svfloat16x2_t_val);
  svcvt_u16(svfloat32x2_t_val);
  svcvt_u16_f32_x2(svfloat32x2_t_val);
  svcvt_u32(svfloat64x2_t_val);
  svcvt_u32_f64_x2(svfloat64x2_t_val);
  svcvtb_f16_s8(svint8_t_val);
  svcvtb_f16_u8(svuint8_t_val);
  svcvtb_f32_s16(svint16_t_val);
  svcvtb_f32_u16(svuint16_t_val);
  svcvtb_f64_s32(svint32_t_val);
  svcvtb_f64_u32(svuint32_t_val);
  svcvtt_f16_s8(svint8_t_val);
  svcvtt_f16_u8(svuint8_t_val);
  svcvtt_f32_s16(svint16_t_val);
  svcvtt_f32_u16(svuint16_t_val);
  svcvtt_f64_s32(svint32_t_val);
  svcvtt_f64_u32(svuint32_t_val);
}
